before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
  - sudo apt-get install libXxf86vm-dev
script:
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - git checkout 3.0.3
  - cmake -DBUILD_SHARED_LIBS=ON
  - make
  - sudo make install
  - cd ..
  - mkdir lib
  - rustc --out-dir lib src/glfw/lib.rs
  - mkdir bin
  - rustc -L lib --out-dir bin src/examples/callbacks.rs
  - rustc -L lib --out-dir bin src/examples/clipboard.rs
  - rustc -L lib --out-dir bin src/examples/cursor.rs
  - rustc -L lib --out-dir bin src/examples/defaults.rs
  - rustc -L lib --out-dir bin src/examples/manual-init.rs
  - rustc -L lib --out-dir bin src/examples/modes.rs
  - rustc -L lib --out-dir bin src/examples/title.rs
  - rustc -L lib --out-dir bin src/examples/version.rs
  - rustc -L lib --out-dir bin src/examples/window.rs
