[package]
authors = ["The glfw-rs developers."]
description = "GLFW3 bindings and idiomatic wrapper for Rust."
keywords = ["windowing", "opengl", "vulkan"]
license = "Apache-2.0"
name = "glfw"
readme = "README.md"
repository = "https://github.com/bjz/glfw-rs"
version = "0.11.0"

[dependencies]
bitflags = "0.7"
enum_primitive = "0.1"
libc = "0.2"
log = "0.3"
num = "0.1"
semver = "0.2"

[dependencies.glfw-sys]
optional = true
version = "^3.2"

[dependencies.image]
optional = true
version = "^0.10"

[dependencies.vk-sys]
optional = true
version = "^0.2"

[features]
all = ["image", "vulkan"]
default = ["glfw-sys"]
vulkan = ["vk-sys"]
